INSERT INTO beers (beer_name,brewery,ibu) VALUES ('19th Anniversary Barleywine Style Imperial Stout','Two Brothers Brewing, 43);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('20th Anniversary  IPA','Two Brothers Brewing, 77);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('A Bretter Day','Two Brothers Brewing, 23);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Atom Smasher','Two Brothers Brewing, 22.6);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('German-Style Oktoberfest / Wiesen (Meadow)','Two Brothers Brewing, 29);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Zut Alors','Two Brothers Brewing, 24);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('American-Style Wheat Wine Ale','Two Brothers Brewing, 45);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Wobble','Two Brothers Brewing, 68.2);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Twenty-Plus','Two Brothers Brewing, 42);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('The Bitter End','Two Brothers Brewing, 36);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Sidekick','Two Brothers Brewing, 36.1);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Revelry,'Two Brothers Brewing, 122.9);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Resistance IPA','Two Brothers Brewing, 70);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Prairie Path','Two Brothers Brewing, 19);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Bombay Grab IPA','Whiner', 77);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Bocks of Chocolates','Whiner', 68);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Dogbite Bitter','Whiner',34);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Forbidden Fruit','Whiner',22);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Handsome Mick's Irish Stout','Whiner',44);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Toasted Coconut Porter','Whiner',56);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Tulach Leis','Whiner',30);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Vermont Nugget ESB','Whiner',24);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Steven Sour','Whiner',53);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Grand Slam Baseball Beer','Whiner',61);
INSERT INTO beers (beer_name,brewery,ibu) VALUES ('Burly Irish Ale','Whiner',28);
