INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Alpha King','Three Floyds', 'West Loop', TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Le Tub','Whiner', 'Logan Square',  TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Bud Light','Budweiser', 'River North',  TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Two Hearted Ale','Bell's', 'Bucktown',  TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Totally Roasted','Vandermill', 'Avondale',  TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Anti Hero','Revolution', 'Wicker Park',  TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Troublesome','Off Color', 'Humboldt Park',  TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Little Sumpin','Lagunitas', 'Pilsen',  TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('All Day IPA','Founders', 'South Loop',  TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Alpha King','Three Floyds', 'West Town',  TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Old Style','Old Style', 'Gold Coast',  TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Chicago Pilsner','Baderbrau', 'Bridgeport',  TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Daisy Cutter','Half Acre', 'Hyde Park',  TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Flywheel','Metropolitan Brewing', 'Lakeview',  TRUE);
INSERT INTO beers (beer_name,brewery,beer_neighborhood, popular) VALUES ('Sidekick','Two Brothers Brewing Company', 'Edgewater',  TRUE);